:macro: toc
:toc-title:
:toc-levels: 9

# URI Monitor

image:https://circleci.com/gh/jasonkuhrt/uri-monitor.svg?style=svg["Circle CI", link="https://circleci.com/gh/jasonkuhrt/uri-monitor"]

toc::[]



## Installation

```
npm install --save uri-monitor
```



## Example

```js
import Monitor from 'uri-monitor'

Monitor
.create('https://foo.io', 1500)
.downs
.observe(() => console.warn('Service Down'))
```



## API

### `create`

```haskell
String, Maybe Integer -> Stream MonitorEvent
```

* `URI` The URI that periodic GET requests will be made to.

* `IntervalMS` Optional. Defaults to `1000`. The time between each GET _request_. Note this is _not_ the time between a response and the next _request_. In other words requests are staggered evenly irrespective of the response time. For example:
+
```
--- = Time    Q = Request    R = Response

Q1----R1-Q2-R2----Q3--R3---Q4   ...
^        ^        ^        ^    <== See, periodic
```
+
Requests are configured to timeout at the `IntervalMS` so that there is only ever one pair of request / pending-response at any given time.

The following will cause a request to be considered a failure:

* Request is not responded to within `IntervalMS`

### Sugar

The returned `Stream` instance is monkey patched with filtered variants for common patterns. They are:

#### `.pongs`

<<CheckEvent, `CheckEvents`>> where `isResponsive` is `true`.

#### `.drops`

<<CheckEvent, `CheckEvents`>> where `isResponsive` is `false`.

#### `.ups`

<<ChangedEvent, `ChangedEvents`>> where `isResponsive` is `true`.

#### `.downs`

<<ChangedEvent, `ChangedEvents`>> where `isResponsive` is `false`.



## Types

#### `Stream`

An instance of link:https://github.com/cujojs/most/blob/master/docs/api.md[`most`].

#### `MonitorEvent`

Base event type that all events emitted by an instance of monitor extend.

```yaml
type : String
data : Map
```

#### `CheckedEvent`

Emitted whenever a request is made to the endpoint being monitored. `result` is `SuperagentError` if `isResponsive` is `false` otherwise `SuperagentResponse`.

```yaml
type: "checked"
data:
  isResponsive: Bool
  result: SuperagentError | SuperagentResponse
```

#### `ChangedEvent`

Emitted whenever a ping result is different than the previous one. `result` is `SuperagentError` if `isResponsive` is `false` otherwise `SuperagentResponse`.

```yaml
type: "changed"
data:
  isResponsive: Bool
  result: SuperagentError | SuperagentResponse
```
