:toc: macro
:toc-title:
:toclevels: 9

# URI Monitor

image:https://circleci.com/gh/jasonkuhrt/uri-monitor.svg?style=svg["Circle CI", link="https://circleci.com/gh/jasonkuhrt/uri-monitor"]

toc::[]



## Installation

```
npm install --save uri-monitor
```



## Examples

Basis for following examples:
```js
import Monitor from 'uri-monitor'

const monitor = Monitor.create('https://foo.io', 1500)
```

Monitoring outages:

```js
const serviceChanges = monitor.filter(({ type }) => type === 'change')

serviceChanges
.filter({ data: { isResponsive }} => !isResponsive)
.observe(() => console.warn('Service Down!'))

serviceChanges
.filter({ data: { isResponsive }} => isResponsive)
.observe(() => console.warn('Service Up!'))
```

Monitoring outages via <<convenience-streams-on-stream, `Stream` sugar>>:

```js
monitor
.downs
.observe(() => console.warn('Service Down!'))

serviceChanges
.ups
.observe(() => console.warn('Service Up!'))
```



## API

### `.create`

```haskell
create :: String, Maybe Integer -> Stream MonitorEvent
--        uri     interval
```

* `uri` The URI that periodic GET requests will be made to.

* `interval` Optional, defaults to `1000`. The milliseconds between each request. Note this is _not_ the time between a response and the next request because requests are evenly staggered. For example:
+
```
--- = Time    Q = Request    R = Response

Q1----R1-Q2-R2----Q3--R3---Q4--
^        ^        ^        ^    <== Evenly staggered
```
+
A response cannot temporally leak into the next request because each request is configured to timeout within the `interval`.

The following will cause a request to be considered a failure:

* Request is not responded to within `interval`

### Convenience streams on `Stream`

The <<stream,`Stream`>> returned by <<create, `create`>> is monkey patched with filtered variants for common patterns. They are:

#### `.pongs`

```haskell
pongs :: Stream CheckedEvent
```
<<checkedevent, `CheckedEvents`>> where `data.isResponsive` is `true`.

#### `.drops`

```haskell
drops :: Stream CheckedEvent
```
<<checkedevent, `CheckedEvents`>> where `data.isResponsive` is `false`.

#### `.ups`

```haskell
ups :: Stream ChangedEvent
```
<<changedevent, `ChangedEvents`>> where `data.isResponsive` is `true`.

#### `.downs`

```haskell
ups :: Stream ChangedEvent
```
<<changedevent, `ChangedEvents`>> where `data.isResponsive` is `false`.



## Types

#### `Stream`

An instance of link:https://github.com/cujojs/most/blob/master/docs/api.md[`most`].

#### `MonitorEvent`

Base interface that all emitted events implement. `result` is `SuperagentError` if `isResponsive` is `false` otherwise `SuperagentResponse`.

```yaml
type : String
data :
  isResponsive: Bool
  result: SuperagentError | SuperagentResponse
```

##### `CheckedEvent`

Emitted every time a result of a request is available.

```yaml
type: "checked"
data:
  isResponsive: Bool
  result: SuperagentError | SuperagentResponse
```

##### `ChangedEvent`

Emitted every time a result of a request has a different `isResponsive` value than the previous result.

```yaml
type: "changed"
data:
  isResponsive: Bool
  result: SuperagentError | SuperagentResponse
```
