:toc: macro
:toc-title:
:toclevels: 9

# URI Monitor

image:https://travis-ci.org/jasonkuhrt/uri-monitor.svg?branch=master["Build Status", link="https://travis-ci.org/jasonkuhrt/uri-monitor"]

toc::[]



## Installation

```
npm install --save uri-monitor
```


## API

### Monitor.create

```js
Monitor.create(action : () => Promise<A>, intervalMs : number?): Observable<MonitorEvent<A>>
```

* `action` The async action to recurse. The expected usage is that you are somehow pinging the resource you are interested in monitoring.

* `intervalMs` The milliseconds between each `action` invocation. Defaults to `1000`.

* `returns` An observable stream of monitor events. The observable implementation we use is https://github.com/cujojs/most[`most`].



### MonitorEvent<A>

Every application of `action` returns a regular promise which ultimately resolves or rejects. In the context of a stream of such values, it is useful to have various terms to refer to different states and patterns of state change:

|===
| Event Name | Case
| `pong` | promise resolved
| `drop` | promise rejected
| `check` | case of `pong` or `drop`
| `up` | promise resolved and: previous attempt rejected or was nothing (initial check)
| `down` | promise rejected and: previous attempt resolved or was nothing (initial case)
| `change` | case of `up` or `down`
|===


With this in mind, the structure of a `MonitorEvent` is:

```js
type MonitorEvent<A> = {
  type : string,
  data : {
    isResponsive : boolean,
    result : A,
  }
}
```

And the value of `type` is any of the aforementioned event names.

`result` is the settled value of the promise returned from `action`.

### monitor.<substream>

The observable stream returned by <<create, `create`>> contains **all** events. For example on the first monitor check four events will occur: `check`, `drop | pong`, `change`, `up | down`. But often this is more noise than you want and while it is easy enough to filter the stream (`monitor.filter(...)`) there is an easier way. Each event type has a corresponding property on the main stream whose value is a filtered stream of _just that event_:


##### monitor.checks

##### monitor.pongs

##### monitor.drops

##### monitor.ups

##### monitor.downs
